USE [master]
GO

/****** Object:  Database [VacationalAgency]    Script Date: 31/07/2020 14:28:38 ******/
CREATE DATABASE [VacationalAgency]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VacationalAgency', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VacationalAgency.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VacationalAgency_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VacationalAgency_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VacationalAgency].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VacationalAgency] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VacationalAgency] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VacationalAgency] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VacationalAgency] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VacationalAgency] SET ARITHABORT OFF 
GO

ALTER DATABASE [VacationalAgency] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VacationalAgency] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VacationalAgency] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VacationalAgency] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VacationalAgency] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VacationalAgency] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VacationalAgency] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VacationalAgency] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VacationalAgency] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VacationalAgency] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VacationalAgency] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VacationalAgency] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VacationalAgency] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VacationalAgency] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VacationalAgency] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VacationalAgency] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VacationalAgency] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VacationalAgency] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [VacationalAgency] SET  MULTI_USER 
GO

ALTER DATABASE [VacationalAgency] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VacationalAgency] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VacationalAgency] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VacationalAgency] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VacationalAgency] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VacationalAgency] SET QUERY_STORE = OFF
GO

ALTER DATABASE [VacationalAgency] SET  READ_WRITE 
GO


